
["Beyond Earth Config"]
	#Enable or Disable Alien to Spawn
	"Alien Spawn" = false
	#Enable or Disable Alien Zombie to Spawn
	"Alien Zombie Spawn" = false
	#Enable or Disable Star Crawler to Spawn
	"Star Crawler Spawn" = false
	#Enable or Disable Pygro to Spawn
	"Pygro Spawn" = false
	#Enable or Disable Pygro Brute to Spawn
	"Pygro Brute Spawn" = false
	#Enable or Disable Mogler to Spawn
	"Mogler Spawn" = false
	#Enable or Disable Martian Raptor to Spawn
	"Martian Raptor Spawn" = false
	#Enable or Disable Player Oxygen System
	"Player Oxygen System" = true
	#Enable or Disable Entity Oxygen System
	"Entity Oxygen System" = true

