
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#Можно ли генерировать корабли снабжения и лагеря в сундуках с награбленным добром. [По умолчанию: true]
	generatesupplyloot = true

